# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/01_base.ipynb.

# %% auto 0
__all__ = ['SEPARATOR_TOKEN', 'Message', 'Conversation', 'Config', 'Prompt']

# %% ../notebooks/01_base.ipynb 2
from dataclasses import dataclass
from typing import Optional, List

# %% ../notebooks/01_base.ipynb 3
SEPARATOR_TOKEN = '<|endoftext|>'

# %% ../notebooks/01_base.ipynb 4
@dataclass(frozen=True)
class Message:
    user: str
    text: Optional[str] = None

    def render(self):
        result = self.user + ':'
        if self.text is not None:
            result += ' ' + self.text
        return result

# %% ../notebooks/01_base.ipynb 5
@dataclass
class Conversation:
    messages: List[Message]

    def prepend(self, message: Message):
        self.messages.insert(0, message)
        return self

    def render(self):
        return f'\n{SEPARATOR_TOKEN}'.join(
            [message.render() for message in self.messages]
        )

# %% ../notebooks/01_base.ipynb 6
@dataclass(frozen=True)
class Config:
    name: str
    instructions: str
    example_conversations: List[Conversation]

# %% ../notebooks/01_base.ipynb 7
@dataclass(frozen=True)
class Prompt:
    header: Message
    examples: List[Conversation]
    convo: Conversation

    def render(self):
        return f'\n{SEPARATOR_TOKEN}'.join(
            [self.header.render()]
            + [Message('System', 'Example conversations:').render()]
            + [conversation.render() for conversation in self.examples]
            + [Message('System', 'Current conversation:').render()]
            + [self.convo.render()],
        )
