# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/12-free-mind.ipynb.

# %% auto 0
__all__ = []

# %% ../notebooks/12-free-mind.ipynb 2
from flask import Flask
from revChatGPT.V1 import Chatbot, configure


app = Flask(__name__)
bot = Chatbot(
    config = configure(),
    conversation_id = 'fdf52ab3-f8c1-450f-86f2-5a25d43fc48d',
    lazy_loading = True
)


@app.route('/<string:prompt>')
def answer(prompt):
    for response in bot.ask(prompt):
        pass
    return response['message']


if __name__ == '__main__':
    app.run(threaded=False)
