# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/11-mind.ipynb.

# %% auto 0
__all__ = []

# %% ../notebooks/11-mind.ipynb 2
from flask import Flask
app = Flask(__name__)

# %% ../notebooks/11-mind.ipynb 3
import openai

# %% ../notebooks/11-mind.ipynb 4
@app.route('/<string:prompt>')
def answer(prompt):
    res = openai.Completion.create(
        engine = 'text-davinci-003',
        prompt = f'{prompt}\n',
        max_tokens = 1024,
        temperature = 0,
        top_p = 0.9,
        frequency_penalty = 0,
        presence_penalty = 0,
        stop = None,
    )
    return res.get('choices', [{}])[0].get('text', '').strip()

# %% ../notebooks/11-mind.ipynb 5
if __name__ == '__main__':
    app.run()
