# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/12-free-mind.ipynb.

# %% auto 0
__all__ = []

# %% ../notebooks/12-free-mind.ipynb 2
from flask import Flask, request
from ipymock.mock import start_conversation as ask

# %% ../notebooks/12-free-mind.ipynb 3
app = Flask(__name__)

@app.route('/')
def answer():
    prompt = request.args.get('q')
    for response in ask(prompt):
        pass
    return response

# %% ../notebooks/12-free-mind.ipynb 4
if __name__ == '__main__':
    app.run(threaded=False)
